### ISSUE TITLE
PG::UndefinedTable: ERROR: relation "mautic_connections" does not exist

### ISSUE THREAD

**Issue by petebytes** [luk4s/mautic-rails#10]
Initial installation Rails 6
I followed the readme, but when starting the application I see this error.

PG::UndefinedTable: ERROR: relation "mautic_connections" does not exist LINE 8: WHERE a.attrelid = '"mautic_connections"'::regclass ^

After running db:migrate I do not see any schema changes.
Am I missing an initialize statement? Thanks

**Comment by petebytes** [comment]
Workaround:

Ran 
```bundle exec rake mautic:install:migrations```
```rails db:migrate```

Error - Multiple migrations have the name CreateMauticMauticConnections
Renamed Migration
reran db:migrate

**Comment by luk4s** [comment]
Based on https://github.com/luk4s/mautic-rails/blob/ed38cfdf88536b6d5ae117708fa9a39e8d969aa3/lib/mautic/engine.rb#L10

migrations should append into main_app. Only exception can be condition on line 11.

I just try it for sure with new rails 6 app and it works for me. Can you please share more details? For example path to your app? Or just check condition on your local 🙂 

 I am sorry but I can' reproduce this...

**Comment by petebytes** [comment]
I also tested with new rails 6 app and it worked.
The workaround is ok for me - if others run into the issue we can look furter.
My environment is running in docker containers (my new rails 6 test was native)
