### ISSUE TITLE
A refresh_token is not available

### ISSUE THREAD

**Issue by petebytes** [luk4s/mautic-rails#11]
After adding a new connection I click update and see the message
'Mautic connection updated'

When I look at the connection m = Mautic::Connection.last
It shows the token and refresh_token are nil

When I try to access API, error 
'A refresh_token is not available'

**Comment by luk4s** [comment]
Did you connect it with Mautic? (In mautic > menu > API credentials > oauth2 ..)
Then you need handshake between mautic and your app (= button at the end of connection line "Authorize")

see: https://github.com/luk4s/mautic-rails#create-mautic-connection

**Comment by petebytes** [comment]
@luk4s thanks for the quick response. I guess I am unsure about handshake.

I created the credentials in Mautic
![image](https://user-images.githubusercontent.com/676739/74760864-4c4d4500-5238-11ea-9d8f-a9f3dc9709c9.png)

And created the Connection on the Rails side
![image](https://user-images.githubusercontent.com/676739/74760995-7dc61080-5238-11ea-80e2-ce3b121a8afe.png)

What am I missing?

**Comment by petebytes** [comment]
Found the authorize button :) 
Thanks for your help.
![image](https://user-images.githubusercontent.com/676739/74764875-cb924700-523f-11ea-8d4c-c260005b07fd.png)
