### ISSUE TITLE
404 Error when retrieving data

### ISSUE THREAD

**Issue by petebytes** [luk4s/mautic-rails#12]
Connection looks OK and has token and refresh_token
![image](https://user-images.githubusercontent.com/676739/74766700-cf739880-5242-11ea-87bb-8b2dff5fe2ff.png)

When I try to retreive a contact as per doc, I am seeing the following:

>> contact = m.contact.find(1)
NoMethodError: undefined method `contact' for #<Mautic::Connections::Oauth2:0x000055f20bfb1f78>
Did you mean?  contacts
	from /app/app/views/layouts/application.html.erb:35:in `_app_views_layouts_application_html_erb__999223015529096905_47249017132380'

>> contact = m.contacts.find(1)
Mautic::RecordNotFound: https://mautic.launchmuse.com/api/contacts/1 => 404 Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!
	from /app/app/views/layouts/application.html.erb:35:in `_app_views_layouts_application_html_erb__999223015529096905_47249017132380'
>>  

Here is my setup
![image](https://user-images.githubusercontent.com/676739/74767310-de0e7f80-5243-11ea-8485-2ec5d26374ec.png)

**Comment by luk4s** [comment]
It seems mautic return 404 - I need to ask, is there contact ID=1 in your mautic?
Try `m.contacts.first` #=> it should return first contact in mautic database...

Check `lib/mautic/proxy.rb` for more methods...

And what mautic version do you use?

**Comment by petebytes** [comment]
@luk4s sorry for the delay - the issue was on the Mautic side, had to clear cache in order for the API to work. Thank you very much for making this available.
