### ISSUE TITLE
[Feature] Add Stage to Contact

### ISSUE THREAD

**Issue by EnziinSystem** [luk4s/mautic-rails#23]
Please add the stages parameter to contact because it is very important.

```
rails console

mautic = Mautic::Connection.first
contacts = mautic.contacts.where(search: "email@domain.com")
contact = contacts.first

contact.stage_id
=> nil

contact.stage
=> nil

contact.stages
=> nil
```
The contact by "email@domain.com" in Mautic has stage_id exist.

Thanks.

**Comment by luk4s** [comment]
Hi @EnziinSystem ,
thanks for feedback, can you please more specify what's about it `stage`? I did quick look into Mautic doc and can't find it (https://developer.mautic.org/#get-contact)

thx

**Comment by EnziinSystem** [comment]
Hi,

You can read in the page: https://docs.mautic.org/en/stages

And stage in the left menu.

![stage](https://user-images.githubusercontent.com/25495466/105470045-a9187180-5ccb-11eb-870a-c11dedd81528.png)

**Comment by luk4s** [comment]
Latest released version now include "stage". See https://github.com/luk4s/mautic-rails/blob/master/app/models/mautic/contact.rb#L144, https://github.com/luk4s/mautic-rails/blob/master/app/models/mautic/stage.rb
