### ISSUE TITLE
`type` is a reserved word in Ruby/Rails

### ISSUE THREAD

**Issue by mabdelfattah** [luk4s/mautic-rails#6]
The gem is creating and using a column name called `type` which is a reserved word by Ruby.

http://www.rubymagic.org/posts/ruby-and-rails-reserved-words

**Comment by luk4s** [comment]
Hi, 
If you talk about https://github.com/luk4s/mautic-rails/blob/master/db/migrate/20171028082047_create_mautic_mautic_connections.rb#L4 , you have right, but `type` is reserved for STI implementation and its this case. MauticConnection is base class for Oauth2 (only oauth2 currently) https://github.com/luk4s/mautic-rails/blob/master/app/models/mautic/connections/oauth2.rb.

Or did you think something else?

**Comment by mabdelfattah** [comment]
Yeah, you are right.
