### ISSUE TITLE
Not compatible with Rails 6

### ISSUE THREAD

**Issue by rodrigocvb** [luk4s/mautic-rails#8]
I tried to add this gem, but it's not compatible with my current rails version: 6.0.0. Is there a plan for doing so?

**Comment by luk4s** [comment]
Hello, thanks for using mautic-rails!
What exactly not work ? I see that there is some issue with rspec controller tests - but when I use rspec 4 beta all tests pass.

Can you share log trace please ?

**Comment by rodrigocvb** [comment]
Thanks for your help @luk4s 

I tried to install the gem and after running "bundle" I got this:

bundle
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 6.0.0)

  In Gemfile:
    rails (~> 6.0.0)

    mautic (~> 0.1) was resolved to 0.1.8, which depends on
      rails (~> 4.2, >= 4.2.8)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

---

I'm new to this, so maybe it's my fault. I tried again now and it worked. I'm not sure what I did to be honest. Do you have any idea?

**Comment by rodrigocvb** [comment]
@luk4s I think I remembered what I did differently:

First attempt:
gem 'mautic', '~>0.1' // following readme file

Second attempt:
gem 'mautic', '~> 2.3', '>= 2.3.1' // following rubygems

**Comment by luk4s** [comment]
I update redmine. I glad to hear that now it works for you. 
Reopen issue if there is more about this.
thx
